package com.medicssupport.support.clinical.clinical.model.patient;

import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class PatientDTO {
    private Long patRid;
    private Integer patEntRid;
    private String patMRN;
    private Integer patSeqNo;
    private String patName;
    private String patFullName;
    private String patMiddleName;
    private String patFamilyName;
    private Integer patGenderIndex;
    private String patGenderName;
    private Integer patCasteIndex;
    private Integer patReligionIndex;
    private Integer patBloodGroupIndex;
    private LocalDate patDob;
    private String patAddress;
    private Integer patAreaRid;
    private String patArea;
    private Integer patCityIndex;
    private String patCity;
    private Integer patStateIndex;
    private String patState;
    private Integer patCountryIndex;
    private String patCountry;
    private String patPhone;
    private String patFilePath;
    private String patFileType;
    private Integer patUserRid;
    private Integer patAccountRid;
    private Integer patValid;
    private Integer patModUserRid;
    private LocalDateTime patModDatetime;
    private String patEmail;
    private Integer patTitleIndex;
    private String patTitleName;
    private Integer patMaritalStatusIndex;
    private String patPostalCode;
    private Boolean patIsVip;
    private Integer patDocContainerRid;
    private Integer patParentPatRid;
    private LocalDate patComputedDob;
    private LocalDateTime patCreateDatetime;
    private Integer patIsOfflineCreated;
    private String patProvisionalMrn;
    private Integer patType;
    private Integer patCorporateRid;
    private String patEmployeeId;
    private Boolean patHasAlert;
    private Integer portId;
    private LocalDateTime oldRegDate;
    private String patOldMrn;
    private Integer patIsExpired;
    private Integer patMergePatientRid;
    private String patTempMrn;
    private Integer patCreationMode;
    private Integer patTempOnlineRid;
    private LocalDateTime patRegisteredDatetime;
    private String patTehsil;
    private Integer patIsSeniorCitizen;
    private Integer patDistrict;
    private String patExternalId;
    private Boolean patIsUnknown;
    private String patMarksForIdentification;
    private Integer portOrgPatRid;
    private Integer patOldApptRid;
    private Boolean patIsPorted;
    private Integer patEnterpriseRid;
}
