package com.medicssupport.support.clinical.clinical.model.staff;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class StaffDTO {

    private Long staffRid;
    private String staffName;
    private String staffAbbrv;
    private String staffCode;
    private String staffAddress;
    private String staffCity;
    private String staffState;
    private String staffCountry;
    private Integer staffCategory;
    private String staffPanCardNo;
    private Long staffUserRid;
    private Integer staffPatientRid;
    private Integer staffResourceRid;
    private String staffSpecialityAbbrv;
    private Long staffEntityRid;
    private Integer staffUnitRid;
    private LocalDate staffDoj;
    private LocalDate staffDol;
    private LocalDate staffContractFrom;
    private LocalDate staffContractTo;
    private Boolean staffValid;
    private Long staffModUserRid;
    private LocalDateTime staffModDatetime;
    private Boolean staffRowInvalidated;
    private Float staffCompensation;
    private Integer staffIsConsultant;
    private Integer staffIsExtDoctor;
    private Integer staffCanRefer;
    private Integer staffRefRid;
    private Integer staffIsAdmittingDoctor;
    private Integer staffIsPrimaryAdmitDoc;
    private Integer staffDesignationIndex;
    private String staffDesignation;
    private String staffQualification;
    private String staffRegistrationNum;
    private Float staffFirstConsultationFee;
    private Float staffFollowUpConsFee;
    private LocalDateTime staffCreatedDatetime;
    private Integer staffHasMultiLocAccess;
    private Integer staffSubCategoryIndex;
    private Integer staffSpecialityIndex;
    private String staffSpecialityName;
    private Integer staffSecondarySpecialityIndex;
    private String staffSecondarySpecialityName;
    private Integer staffTertiarySpecialityIndex;
    private String staffTertiarySpecialityName;
    private Integer staffToBeRostered;
    private Integer portStaffId;
    private String staffEmailId;
    private String staffMobile;
    private Integer staffEligibilityRid;
    private Integer staffIsSchedulable;
    private Integer staffDummy1;
    private String staffBankAccNo;
    private Integer staffMaxConsultationNo;
    private String staffDigitalSignature;
    private Integer staffTitle;
    private Integer staffParentRid;
    private Integer staffPaymentMethod;
    private Integer staffCreditPeriod;
    private String staffBankName;
    private String staffBankBranch;
    private String staffIfscCode;
    private Integer staffIsSystemDefined;
    private String staffAccountNumber;
    private Integer staffIsServiceProvider;
    private Boolean staffUpdateMyApptToGcal;
    private Integer portStaffURid;
    private Integer staffManuallyPorted;
    private Integer staffOldUnitRid;
    private Integer staffOldStaffRid;
    private String staffNameInReginalFont;
    private Integer staffTypeIndex;
    private Integer staffFreeVisitCount;
    private Integer staffFreeVisitValidity;
    private Integer staffIsRequiredConsultationFee;
    private Integer staffIsRequiredConsultationFeeIp;
    private Integer staffFreeVisitCountIp;
    private Integer staffFreeVisitValidityIp;
    private Integer staffIsSchedulableOnline;
    private Integer staffReportingTime;
    private String staffExternalId;
    private Integer staffCanPerformVideoConsultation;
    private Integer staffCanHandleCovidPatients;
    private Integer staffGradeIndex;
    private Integer staffIsUser;
    private Integer staffOldRid;
    private String staffTokenPrefix;
    private String staffPastExperience;
    private String staffDescription;
    private Integer staffNicSpecialityRid;
    private Integer staffIsRemoteUser;
}
